name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.11'
      - run: pip install -e ".[dev]" pytest-cov
      - name: Unit & parity
        run: |
          pytest -q --cov=protosynth --cov-report=xml tests
          python scripts/staged_parity_harness.py  # asserts F_eval ≈ F*
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
      - name: Smoke evolve
        run: |
          protosynth-evolve --env periodic_k4 --gens 40 --k 4 --mu 8 --lambda 16 --seed 1
          protosynth-evolve --env markov_k2   --gens 40 --k 2 --mu 8 --lambda 16 --seed 2
